apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: 35.185.187.150:8000/root/gateway:__TAG__
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: EUREKA_SERVER_URL
              value: "http://eureka-server:8761/eureka/"
            - name: JWT_SECRET
              value: "vdt_cloud_phase1_jwt_secret_key_long_enough_32_bytes"
            - name: CORS_ALLOWED_ORIGINS
              value: "http://localhost:*,http://127.0.0.1:*"
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/agents/opentelemetry-javaagent.jar -Xmx256m"
            - name: OTEL_SERVICE_NAME
              value: "gateway"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_METRICS_EXPORTER
              value: "none"
            - name: OTEL_LOGS_EXPORTER
              value: "none"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://tempo:4318"
          volumeMounts:
            - name: agents-volume
              mountPath: /agents
      volumes:
        - name: agents-volume
          hostPath:
            path: /home/nguyentridung20044/mid-project-135890-main/agents
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: gateway
