server:
  port: ${SERVER_PORT:8086}

spring:
  application:
    name: notification-service
  docker:
    compose:
      enabled: false
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3312/notification_service_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    properties:
      "[hibernate.format_sql]": true
      "[hibernate.dialect]": org.hibernate.dialect.MySQLDialect
    open-in-view: false
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD}
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.transport.protocol: smtp

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${HOSTNAME:local}:${server.port}

jwt:
  secret: ${JWT_SECRET}

app:
  rabbitmq:
    exchange: exam.events
    exam-submitted-queue: notification.exam.submitted
    exam-submitted-routing-key: exam.submitted
    class-user-added-queue: notification.class.user.added
    class-user-added-routing-key: class.user.added
    exam-created-queue: notification.exam.created
    exam-created-routing-key: exam.created
    auth-user-registered-queue: notification.auth.user.registered
    auth-user-registered-routing-key: auth.user.registered
  mail:
    from-email: ${MAIL_FROM_EMAIL}
    from-name: ${MAIL_FROM_NAME:E-Mid Quiz System}
